### PR TITLE
Refactor/sort/bubble

### PR DESCRIPTION
**Pull request by yxyx-github**
This PR includes:
- #15 refactor bubblesort
- #16 implement sort algorithm form
- minor layout fixes
- generate additional steps for bubblesort
- scale down all UI elements

### CODE REVIEW

**Comment by yxyx-github** [comment]
known issues for following custom inputs:
3,5, 1,  4
3,5, 1,  4, a
3,5, 1,  4, 4 2

**Comment by yxyx-github** [comment]
Parsing custom inputs is fixed now.

**Review by termitehuegel — CHANGES_REQUESTED** [review]
looks good, but we might need to think about the scaling of the visualisation (Try 1000 Numbers or a Maxnumber of 2000). But please increase the Playbackrate to 25 FPS (40ms Intervall).

**Review by termitehuegel — APPROVED** [review]

**Comment by yxyx-github** [comment]
Requested changes will be implemented in another PR.

**Pull request merged**
